spring.application.name=api-gateway
server.port=${API_GATEWAY_PORT}

# Eureka client configuration
eureka.client.service-url.defaultZone=${EUREKA_URL}

# Spring Cloud Gateway routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/oauth2/**,/login/**

spring.cloud.gateway.routes[1].id=project-service
spring.cloud.gateway.routes[1].uri=lb://project-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/projects/**

spring.cloud.gateway.routes[2].id=file-service
spring.cloud.gateway.routes[2].uri=lb://file-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/files/**

spring.cloud.gateway.routes[3].id=session-service
spring.cloud.gateway.routes[3].uri=lb://session-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/sessions/**

spring.cloud.gateway.routes[4].id=execution-service
spring.cloud.gateway.routes[4].uri=lb://execution-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/executions/**

spring.cloud.gateway.routes[5].id=version-service
spring.cloud.gateway.routes[5].uri=lb://version-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/versions/**

spring.cloud.gateway.routes[6].id=comment-service
spring.cloud.gateway.routes[6].uri=lb://comment-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/comments/**

spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://notification-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/notifications/**,/notifications-ws/**

spring.cloud.gateway.routes[8].id=website-controller
spring.cloud.gateway.routes[8].uri=lb://website-controller
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/web/**

spring.cloud.gateway.routes[9].id=session-ws
spring.cloud.gateway.routes[9].uri=lb://session-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/sessions-ws/**

spring.cloud.gateway.routes[10].id=payment-service
spring.cloud.gateway.routes[10].uri=lb://payment-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/payments/**

spring.cloud.gateway.routes[11].id=yjs-ws
spring.cloud.gateway.routes[11].uri=lb://session-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/yjs/**

