spring.application.name=file-service
spring.config.import=optional:file:../.env[.properties]

server.port=${FILE_SERVICE_PORT:8083}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

# File upload config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom storage path
file.upload-dir=uploads

# MySQL Database
spring.datasource.url=${FILE_DB_URL}
spring.datasource.username=${FILE_DB_USERNAME}
spring.datasource.password=${FILE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Show actual error messages in API responses
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
