spring.application.name=session-service
server.port=${SESSION_SERVICE_PORT}

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${EUREKA_HOSTNAME}

# Redis config (Spring Boot 3 uses spring.data.redis)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# MySQL Database
spring.datasource.url=${SESSION_DB_URL}
spring.datasource.username=${SESSION_DB_USERNAME}
spring.datasource.password=${SESSION_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
