spring.application.name=project-service
server.port=${PROJECT_SERVICE_PORT}

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${EUREKA_HOSTNAME}

spring.datasource.url=${PROJECT_DB_URL}
spring.datasource.username=${PROJECT_DB_USERNAME}
spring.datasource.password=${PROJECT_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

