spring.application.name=execution-service
spring.config.import=optional:file:../.env[.properties]

server.port=${EXECUTION_SERVICE_PORT:8085}

spring.datasource.url=${EXECUTION_DB_URL}
spring.datasource.username=${EXECUTION_DB_USERNAME}
spring.datasource.password=${EXECUTION_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Execution Config
execution.timeout.ms=10000
execution.memory.limit=512mb

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

