spring.application.name=version-service
spring.config.import=optional:file:../.env[.properties]

server.port=${VERSION_SERVICE_PORT:8088}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
	
# MySQL Database
spring.datasource.url=${VERSION_DB_URL}
spring.datasource.username=${VERSION_DB_USERNAME}
spring.datasource.password=${VERSION_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

