spring.application.name=version-service
server.port=${VERSION_SERVICE_PORT}

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${EUREKA_HOSTNAME}
	
# MySQL Database
spring.datasource.url=${VERSION_DB_URL}
spring.datasource.username=${VERSION_DB_USERNAME}
spring.datasource.password=${VERSION_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

