spring.application.name=eureka-server
spring.config.import=optional:file:../.env[.properties]

server.port=${EUREKA_SERVER_PORT:8761}

# Don't register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}


